# Generated by Django 6.0.1 on 2026-01-23 08:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewed_id', models.UUIDField(verbose_name='ID объекта отзыва')),
                ('target_type', models.CharField(choices=[('inventory', 'Инвентарь'), ('user', 'Пользователь')], max_length=20, verbose_name='Тип объекта')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('published', 'Опубликован'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус')),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отзыва')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('punctuality_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка пунктуальности')),
                ('condition_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка состояния')),
                ('communication_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка общения')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rentals.rental', verbose_name='Аренда')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'reviews',
                'ordering': ['-review_date'],
                'indexes': [models.Index(fields=['reviewed_id', 'target_type', 'status'], name='reviews_reviewe_df0d56_idx'), models.Index(fields=['reviewer', 'status'], name='reviews_reviewe_fdb5b1_idx')],
                'constraints': [models.UniqueConstraint(fields=('rental', 'reviewer', 'target_type'), name='unique_review_per_rental_reviewer_target')],
            },
        ),
    ]
