# Generated by Django 6.0.1 on 2026-01-23 08:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rental_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('actual_return_date', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата возврата')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общая стоимость')),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Внесенный залог')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('rejected', 'Отклонена')], default='pending', max_length=30, verbose_name='Статус')),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('refunded', 'Возвращено'), ('failed', 'Ошибка оплаты')], default='pending', max_length=20, verbose_name='Статус оплаты')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='users.client', verbose_name='Клиент')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='inventory.inventory', verbose_name='Инвентарь')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_rentals', to='users.manager', verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
                'db_table': 'rentals',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('payment_method', models.CharField(choices=[('card', 'Банковская карта'), ('cash', 'Наличные'), ('online', 'Онлайн-платеж'), ('transfer', 'Банковский перевод')], max_length=30, verbose_name='Способ оплаты')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID транзакции')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('completed', 'Завершен'), ('failed', 'Ошибка'), ('refunded', 'Возвращен')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата платежа')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма возврата')),
                ('refund_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='rentals.rental', verbose_name='Аренда')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'db_table': 'payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('damage_type', models.CharField(choices=[('minor', 'Незначительное'), ('moderate', 'Среднее'), ('major', 'Серьезное'), ('critical', 'Критическое')], max_length=50, verbose_name='Тип повреждения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='damage_reports/', verbose_name='Фото повреждений')),
                ('status', models.CharField(choices=[('reported', 'Сообщено'), ('reviewing', 'На рассмотрении'), ('resolved', 'Решено'), ('disputed', 'Оспаривается')], default='reported', max_length=20, verbose_name='Статус')),
                ('repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость ремонта')),
                ('reported_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата сообщения')),
                ('resolved_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата решения')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='inventory.inventory', verbose_name='Инвентарь')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сообщивший')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='rentals.rental', verbose_name='Аренда')),
            ],
            options={
                'verbose_name': 'Отчет о повреждении',
                'verbose_name_plural': 'Отчеты о повреждениях',
                'db_table': 'damage_reports',
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Номер договора')),
                ('terms', models.TextField(verbose_name='Условия договора')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='Дата подписания')),
                ('pdf_url', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='PDF договора')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус')),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='rentals.rental', verbose_name='Аренда')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'db_table': 'contracts',
                'ordering': ['-signed_date'],
            },
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['client', 'status'], name='rentals_client__3149ab_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['inventory', 'status'], name='rentals_invento_c58f56_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['start_date', 'end_date'], name='rentals_start_d_2c8f7d_idx'),
        ),
    ]
