# Generated by Django 5.2.10 on 2026-01-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('inquiry', 'Вопрос по инвентарю'), ('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('rejected', 'Отклонена')], default='pending', max_length=30, verbose_name='Статус'),
        ),
    ]
