# Generated by Django 5.2.10 on 2026-02-05 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rental_status'),
        ('users', '0002_bankaccount_owneragreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals', to='users.bankaccount', verbose_name='Банковский счет для выплаты'),
        ),
    ]
