# Generated by Django 5.2.10 on 2026-02-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rental_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='additional_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доплата за продление'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('inquiry', 'Вопрос по инвентарю'), ('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('active', 'Активна'), ('delayed', 'Задержка'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('rejected', 'Отклонена')], default='pending', max_length=30, verbose_name='Статус'),
        ),
    ]
