# Generated by Django 5.2.10

from django.db import migrations


def move_delayed_to_payment_status(apps, schema_editor):
    Rental = apps.get_model('rentals', 'Rental')
    Rental.objects.filter(status='delayed').update(status='active', payment_status='delayed')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rental_additional_payment_alter_rental_status'),
    ]

    operations = [
        migrations.RunPython(move_delayed_to_payment_status, noop),
    ]
