# Generated by Django 5.2.10 on 2026-02-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_move_delayed_to_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('delayed', 'Задержка оплаты'), ('refunded', 'Возвращено'), ('failed', 'Ошибка оплаты')], default='pending', max_length=20, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('inquiry', 'Вопрос по инвентарю'), ('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('rejected', 'Отклонена')], default='pending', max_length=30, verbose_name='Статус'),
        ),
    ]
