# Generated by Django 5.2.10 on 2026-03-25 07:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_status'),
        ('rentals', '0007_alter_rental_payment_status_alter_rental_status'),
        ('users', '0005_client_passport_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('cancelled', 'Отменена'), ('converted', 'Преобразована в аренду'), ('expired', 'Истекла')], default='active', max_length=30, verbose_name='Статус')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='users.client', verbose_name='Клиент')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.inventory', verbose_name='Инвентарь')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'db_table': 'reservations',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['client', 'status'], name='reservation_client__cdbf35_idx'), models.Index(fields=['inventory', 'status'], name='reservation_invento_41b5ee_idx'), models.Index(fields=['start_date', 'end_date'], name='reservation_start_d_e753a5_idx')],
            },
        ),
    ]
