# Generated by Django 5.2.10 on 2026-05-24 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_reservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='additional_payment_paid',
            field=models.BooleanField(default=False, verbose_name='Продление оплачено'),
        ),
        migrations.AddField(
            model_name='rental',
            name='marked_paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_extension_paid', to=settings.AUTH_USER_MODEL, verbose_name='Оплату наличными зафиксировал'),
        ),
        migrations.AddField(
            model_name='rental',
            name='overdue_fee_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Штраф оплачен'),
        ),
        migrations.AddField(
            model_name='rental',
            name='overdue_fee_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зафиксированный штраф на момент оплаты'),
        ),
    ]
