# Generated by Django 5.2.10 on 2026-05-25 08:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_rental_extension_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('payment_type', models.CharField(choices=[('extension_card', 'Доплата за продление (онлайн)'), ('extension_cash', 'Доплата за продление (наличными)'), ('overdue_card', 'Штраф за просрочку (онлайн)'), ('overdue_cash', 'Штраф за просрочку (наличными)')], max_length=20, verbose_name='Тип платежа')),
                ('paid_at', models.DateTimeField(verbose_name='Дата оплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
                ('paid_to_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_cash_payments', to=settings.AUTH_USER_MODEL, verbose_name='Принял наличными')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='rentals.rental', verbose_name='Аренда')),
            ],
            options={
                'verbose_name': 'История платежа',
                'verbose_name_plural': 'История платежей',
                'db_table': 'payment_history',
                'ordering': ['-paid_at'],
            },
        ),
    ]
