# Generated by Django 5.2.14 on 2026-05-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_add_payment_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='overdue_terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Условия просрочки приняты'),
        ),
    ]
