# Generated by Django 6.0.1 on 2026-01-23 08:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportCategory',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, help_text='CSS класс иконки', max_length=50, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'sport_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Бренд')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за день')),
                ('condition', models.CharField(choices=[('new', 'Новое'), ('excellent', 'Отличное'), ('good', 'Хорошее'), ('fair', 'Удовлетворительное')], default='good', max_length=50, verbose_name='Состояние')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('available', 'Доступен'), ('rented', 'Арендован'), ('maintenance', 'На обслуживании'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('avg_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Средний рейтинг')),
                ('total_rentals', models.IntegerField(default=0, verbose_name='Всего аренд')),
                ('min_rental_days', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Минимум дней аренды')),
                ('max_rental_days', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимум дней аренды')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма залога')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_items', to='users.manager', verbose_name='Менеджер')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='users.owner', verbose_name='Владелец')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.sportcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Инвентарь',
                'verbose_name_plural': 'Инвентарь',
                'db_table': 'inventory',
                'ordering': ['-added_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryPhoto',
            fields=[
                ('photo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_url', models.ImageField(upload_to='inventory_photos/', verbose_name='Фотография')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('uploaded_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.inventory', verbose_name='Инвентарь')),
            ],
            options={
                'verbose_name': 'Фотография инвентаря',
                'verbose_name_plural': 'Фотографии инвентаря',
                'db_table': 'inventory_photos',
                'ordering': ['-is_main', 'uploaded_date'],
            },
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['status', 'category'], name='inventory_status_97306c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['owner', 'status'], name='inventory_owner_i_7e0d46_idx'),
        ),
    ]
