# Generated by Django 5.2.10 on 2026-01-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='reviews_count',
            field=models.IntegerField(default=0, verbose_name='Количество отзывов'),
        ),
    ]
