# Generated by Django 5.2.10 on 2026-02-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_favorite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='favorite',
            new_name='inventory_f_client__ac584e_idx',
            old_name='inventory_f_client__7e3cdb_idx',
        ),
    ]
