# Generated by Django 5.2.10 on 2026-02-05 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_inventory_f_client__7e3cdb_idx_inventory_f_client__ac584e_idx'),
        ('users', '0002_bankaccount_owneragreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='users.bankaccount', verbose_name='Банковский счет для выплаты'),
        ),
    ]
