# Generated by Django 5.2.10 on 2026-02-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает проверки'), ('awaiting_contract', 'Принят и ожидается подписание договора'), ('available', 'Доступен'), ('rented', 'Арендован'), ('maintenance', 'На обслуживании'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
