# Generated by Django 5.2.14 on 2026-05-11 16:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_status'),
        ('users', '0007_add_passport_nda'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('region', models.CharField(blank=True, max_length=150, verbose_name='Регион/область')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('point_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название точки')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон точки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_points', to='inventory.city', verbose_name='Город')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_points', to='users.manager', verbose_name='Менеджер')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_points', to='users.owner', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Точка выдачи',
                'verbose_name_plural': 'Точки выдачи',
                'db_table': 'pickup_points',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='inventory.pickuppoint', verbose_name='Точка выдачи'),
        ),
        migrations.AddIndex(
            model_name='pickuppoint',
            index=models.Index(fields=['city', 'is_active'], name='pickup_poin_city_id_77cfd4_idx'),
        ),
    ]
