# Generated by Django 6.0.1 on 2026-01-23 08:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Телефон')),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('owner', 'Владелец'), ('manager', 'Менеджер'), ('administrator', 'Администратор')], default='client', max_length=30, verbose_name='Роль')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('blocked', 'Заблокирован'), ('pending', 'Ожидает проверки')], default='active', max_length=20, verbose_name='Статус')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('avatar_url', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('avg_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Средний рейтинг')),
                ('loyalty_points', models.IntegerField(default=0, verbose_name='Баллы лояльности')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('email_work', models.EmailField(max_length=255, verbose_name='Рабочий email')),
                ('actions_logged', models.IntegerField(default=0, verbose_name='Количество действий')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
                'db_table': 'administrators',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('passport_data', models.TextField(blank=True, verbose_name='Паспортные данные')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('total_rentals', models.IntegerField(default=0, verbose_name='Всего аренд')),
                ('verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('loyalty_points', models.IntegerField(default=0, verbose_name='Баллы лояльности')),
                ('preferred_payment', models.CharField(blank=True, choices=[('card', 'Банковская карта'), ('cash', 'Наличные'), ('online', 'Онлайн-платеж')], max_length=30, verbose_name='Предпочитаемый способ оплаты')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('phone_work', models.CharField(blank=True, max_length=15, verbose_name='Рабочий телефон')),
                ('email_work', models.EmailField(blank=True, max_length=255, verbose_name='Рабочий email')),
                ('assigned_items', models.IntegerField(default=0, verbose_name='Назначенных предметов')),
                ('active_chats', models.IntegerField(default=0, verbose_name='Активных чатов')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
                'db_table': 'managers',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ИНН')),
                ('bank_details', models.TextField(blank=True, verbose_name='Банковские реквизиты')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общий заработок')),
                ('active_items', models.IntegerField(default=0, verbose_name='Активных предметов')),
                ('verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Владелец',
                'verbose_name_plural': 'Владельцы',
                'db_table': 'owners',
            },
        ),
    ]
