# Generated by Django 5.2.10 on 2026-02-05 17:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=200, verbose_name='Название банка')),
                ('account_number', models.CharField(max_length=50, verbose_name='Номер счета')),
                ('bik', models.CharField(blank=True, max_length=20, verbose_name='БИК')),
                ('correspondent_account', models.CharField(blank=True, max_length=50, verbose_name='Корреспондентский счет')),
                ('recipient_name', models.CharField(max_length=200, verbose_name='Получатель')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН получателя')),
                ('kpp', models.CharField(blank=True, max_length=20, verbose_name='КПП')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='users.owner', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Банковский счет',
                'verbose_name_plural': 'Банковские счета',
                'db_table': 'bank_accounts',
                'ordering': ['-is_default', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='OwnerAgreement',
            fields=[
                ('agreement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент владельцу')),
                ('store_percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент магазину')),
                ('agreement_text', models.TextField(verbose_name='Текст соглашения')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Принято')),
                ('accepted_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='users.owner', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Соглашение владельца',
                'verbose_name_plural': 'Соглашения владельцев',
                'db_table': 'owner_agreements',
                'ordering': ['-created_date'],
            },
        ),
    ]
