# Generated by Django 5.2.10 on 2026-02-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bankaccount_owneragreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='bik',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='correspondent_account',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='kpp',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=19, verbose_name='Номер счета'),
        ),
    ]
