# Generated by Django 5.2.10 on 2026-02-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_bankaccount_bik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_reason',
            field=models.TextField(blank=True, verbose_name='Причина блокировки'),
        ),
    ]
