# Generated by Django 5.2.10 on 2026-04-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_client_passport_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='phone_work',
            field=models.CharField(blank=True, max_length=30, verbose_name='Рабочий телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Телефон'),
        ),
    ]
