# Generated by Django 5.2.14 on 2026-05-11 14:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_manager_phone_work_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportNDA',
            fields=[
                ('nda_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(default='v1.0', max_length=10, verbose_name='Версия соглашения')),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата принятия')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_ndas', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Соглашение на паспортные данные',
                'verbose_name_plural': 'Соглашения на паспортные данные',
                'db_table': 'passport_nda',
                'ordering': ['-accepted_at'],
            },
        ),
    ]
