# Generated by Django 5.2.10 on 2026-05-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_owner_home_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_super_manager',
            field=models.BooleanField(default=False, verbose_name='Супер-менеджер'),
        ),
    ]
