# Generated by Django 5.2.14 on 2026-05-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_is_super_manager_to_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='passport_department_code',
            field=models.CharField(blank=True, max_length=7, verbose_name='Код подразделения'),
        ),
        migrations.AddField(
            model_name='owner',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='owner',
            name='passport_issued_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='owner',
            name='passport_nda_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='NDA принято'),
        ),
        migrations.AddField(
            model_name='owner',
            name='passport_nda_version',
            field=models.CharField(blank=True, max_length=20, verbose_name='Версия NDA'),
        ),
        migrations.AddField(
            model_name='owner',
            name='passport_number',
            field=models.CharField(blank=True, max_length=6, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='owner',
            name='passport_series',
            field=models.CharField(blank=True, max_length=4, verbose_name='Серия паспорта'),
        ),
    ]
