# Generated by Django 6.0.1 on 2026-01-23 08:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('file', 'Файл'), ('system', 'Системное')], default='text', max_length=20, verbose_name='Тип сообщения')),
                ('file_url', models.FileField(blank=True, null=True, upload_to='chat_files/', verbose_name='Файл')),
                ('sent_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отправки')),
                ('read_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='rentals.rental', verbose_name='Аренда')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'db_table': 'chat_messages',
                'ordering': ['sent_date'],
                'indexes': [models.Index(fields=['rental', 'sent_date'], name='chat_messag_rental__dcd420_idx'), models.Index(fields=['sender', 'receiver'], name='chat_messag_sender__8af08b_idx')],
            },
        ),
    ]
