# Generated by Django 5.2.14 on 2026-05-25 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0011_rental_overdue_terms_accepted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('intent_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID намерения')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма (руб.)')),
                ('purpose', models.CharField(choices=[('rental_main', 'Основная оплата аренды'), ('extension', 'Доплата за продление'), ('overdue', 'Штраф за просрочку')], max_length=20, verbose_name='Назначение платежа')),
                ('yookassa_payment_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID платежа в ЮКассе')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('waiting_for_capture', 'Ожидает подтверждения'), ('succeeded', 'Оплачен'), ('canceled', 'Отменён')], default='pending', max_length=25, verbose_name='Статус')),
                ('raw_webhook_data', models.JSONField(default=dict, verbose_name='Сырые данные webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='rentals.rental', verbose_name='Аренда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to=settings.AUTH_USER_MODEL, verbose_name='Плательщик')),
            ],
            options={
                'verbose_name': 'Намерение оплаты',
                'verbose_name_plural': 'Намерения оплаты',
                'ordering': ['-created_at'],
            },
        ),
    ]
